// 40 sample NYC events for testing
// _sample: true marks these as auto/sample (not user submitted)
// Toggle SAMPLE_MODE in lib/sampleConfig.js to hide all sample data
import { SAMPLE_MODE } from './sampleConfig';
const ALL_SAMPLE_EVENTS = [
  {
    id: 'sample-1',
    name: 'NYC Botanical Gardens',
    event_name: 'The Orchid Show: Mr. Flower Fantastic\'s Concrete Jungle',
    price_category: '$$',
    location_data: { city: 'Bronx', address: '2900 Southern Blvd, Bronx, NY', zipcode: '10458' },
    event_date: '2026-04-15',
    event_time_utc: '2026-04-15T14:00:00Z',
    relevant_links: ['https://www.nybg.org'],
    description: 'Thousands of orchids transforming the conservatory into a bloom-laden remix of NYC street life. Taxis, bodegas, and subway scenes made entirely of flowers.',
    photos: [
      'https://images.unsplash.com/photo-1490750967868-88df5691cc10?w=600',
      'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=600',
      'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=600',
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600',
    ],
    representative_emoji: '🌸',
    hex_color: '#FF6B9D',
    is_approved: true,
    _sample: true,
    _sample: true,
    borough: 'Bronx',
    lat: 40.8623,
    lng: -73.8812,
  },
  {
    id: 'sample-2',
    name: 'The Metropolitan Museum of Art',
    event_name: 'Raphael: Sublime Poetry at the Met',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '1000 5th Ave, New York, NY', zipcode: '10028' },
    event_date: '2026-04-20',
    event_time_utc: '2026-04-20T10:00:00Z',
    relevant_links: ['https://www.metmuseum.org'],
    description: 'The first comprehensive US exhibition of Italian Renaissance master Raphael. Over 200 drawings, paintings, tapestries from his life in Urbino, Florence and Rome.',
    photos: [
      'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=600',
      'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600',
      'https://images.unsplash.com/photo-1617503752587-97d2103a96ea?w=600',
    ],
    representative_emoji: '🎨',
    hex_color: '#FF4500',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7794,
    lng: -73.9632,
  },
  {
    id: 'sample-3',
    name: 'Edge NYC',
    event_name: 'Bridgerton Candlelight Evenings at Edge',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '30 Hudson Yards, New York, NY', zipcode: '10001' },
    event_date: '2026-04-10',
    event_time_utc: '2026-04-10T19:00:00Z',
    relevant_links: ['https://www.edgenyc.com'],
    description: 'Enjoy a Bridgerton-themed candlelight experience atop the highest sky deck in the Western Hemisphere with string quartet performances and champagne.',
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=600',
    ],
    representative_emoji: '🕯️',
    hex_color: '#FFD700',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7539,
    lng: -74.0005,
  },
  {
    id: 'sample-4',
    name: 'NYC Events',
    event_name: 'St. Patrick\'s Day Parade on Fifth Avenue',
    price_category: 'free',
    location_data: { city: 'Manhattan', address: '5th Ave, New York, NY', zipcode: '10022' },
    event_date: '2026-03-17',
    event_time_utc: '2026-03-17T11:00:00Z',
    relevant_links: ['https://www.nycstpatricksparade.org'],
    description: 'The world\'s oldest civilian parade marches down Fifth Avenue with bagpipers, dancers, and festive cheer. Millions of spectators line the route.',
    photos: ['https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?w=400'],
    representative_emoji: '☘️',
    hex_color: '#00C851',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7580,
    lng: -73.9775,
  },
  {
    id: 'sample-5',
    name: 'Beacon Theatre',
    event_name: 'Love Rocks NYC Benefit Concert',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '2124 Broadway, New York, NY', zipcode: '10023' },
    event_date: '2026-03-05',
    event_time_utc: '2026-03-05T20:00:00Z',
    relevant_links: ['https://www.beacontheatre.com'],
    description: 'Star-studded benefit concert featuring Paul Simon, Mary J. Blige, Hozier, and Nile Rodgers & CHIC. Benefits God\'s Love We Deliver.',
    photos: ['https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600',
      'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600',
      'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600',
    ],
    representative_emoji: '🎸',
    hex_color: '#6C63FF',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7806,
    lng: -73.9813,
  },
  {
    id: 'sample-6',
    name: 'Madison Square Garden',
    event_name: 'Big East Basketball Tournament',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '4 Pennsylvania Plaza, New York, NY', zipcode: '10001' },
    event_date: '2026-03-12',
    event_time_utc: '2026-03-12T18:00:00Z',
    relevant_links: ['https://www.msg.com'],
    description: 'College basketball returns to the legendary Madison Square Garden for the Big East Tournament semifinals and finals.',
    photos: ['https://images.unsplash.com/photo-1546519638405-a9f14e610c99?w=600',
      'https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=600',
    ],
    representative_emoji: '🏀',
    hex_color: '#FF6B00',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7725,
    lng: -73.9835,
  },
  {
    id: 'sample-7',
    name: 'NYC Road Runners',
    event_name: 'United Airlines NYC Half Marathon',
    price_category: '$',
    location_data: { city: 'Brooklyn', address: 'Prospect Park, Brooklyn, NY', zipcode: '11225' },
    event_date: '2026-03-15',
    event_time_utc: '2026-03-15T07:00:00Z',
    relevant_links: ['https://www.nyrr.org'],
    description: '13.1 miles from Brooklyn through Central Park into the heart of Midtown. One of the most electric weekends of the year with tens of thousands of runners.',
    photos: ['https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400'],
    representative_emoji: '🏃',
    hex_color: '#FF3366',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.6933,
    lng: -73.9874,
  },
  {
    id: 'sample-8',
    name: 'NYC Center',
    event_name: 'Flamenco Festival at New York City Center',
    price_category: '$$',
    location_data: { city: 'Manhattan', address: '130 W 56th St, New York, NY', zipcode: '10019' },
    event_date: '2026-03-06',
    event_time_utc: '2026-03-06T19:30:00Z',
    relevant_links: ['https://www.nycitycenter.org'],
    description: 'Dance, music, and passion come alive at the Flamenco Festival in Midtown Manhattan. Stunning performances of traditional and contemporary flamenco.',
    photos: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400'],
    representative_emoji: '💃',
    hex_color: '#FF1744',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7621,
    lng: -73.9684,
  },
  {
    id: 'sample-9',
    name: 'Christie\'s New York',
    event_name: 'Jim Irsay Collection: Music Memorabilia',
    price_category: 'free',
    location_data: { city: 'Manhattan', address: '20 Rockefeller Plaza, New York, NY', zipcode: '10020' },
    event_date: '2026-03-10',
    event_time_utc: '2026-03-10T10:00:00Z',
    relevant_links: ['https://www.christies.com'],
    description: 'The greatest private collection of music memorabilia in the world including Kurt Cobain\'s guitar from the "Smells Like Teen Spirit" video.',
    photos: ['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400'],
    representative_emoji: '🎵',
    hex_color: '#651FFF',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7601,
    lng: -73.9798,
  },
  {
    id: 'sample-10',
    name: 'Rockefeller Center',
    event_name: 'Chef\'s Best at Rockefeller Center',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '45 Rockefeller Plaza, New York, NY', zipcode: '10111' },
    event_date: '2026-03-14',
    event_time_utc: '2026-03-14T19:00:00Z',
    relevant_links: ['https://www.rockefellercenter.com'],
    description: 'One-night-only menus from NYC\'s most acclaimed chefs at Le Rock, NARO, Jupiter and 5 Acres. A curated dining series at the heart of Midtown.',
    photos: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400'],
    representative_emoji: '🍽️',
    hex_color: '#FF9100',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7286,
    lng: -73.9868,
  },
  {
    id: 'sample-11',
    name: 'Brooklyn Museum',
    event_name: 'Dawoud Bey & Carrie Mae Weems: In Dialogue',
    price_category: '$$',
    location_data: { city: 'Brooklyn', address: '200 Eastern Pkwy, Brooklyn, NY', zipcode: '11238' },
    event_date: '2026-04-01',
    event_time_utc: '2026-04-01T11:00:00Z',
    relevant_links: ['https://www.brooklynmuseum.org'],
    description: 'A groundbreaking exhibition placing two major American artists in dialogue for the first time, exploring themes of race, memory, and community.',
    photos: ['https://images.unsplash.com/photo-1578926288207-32356338ffd4?w=400'],
    representative_emoji: '📷',
    hex_color: '#00BCD4',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.6795,
    lng: -73.9795,
  },
  {
    id: 'sample-12',
    name: 'Brooklyn Brewery',
    event_name: 'Brooklyn Craft Beer Festival Spring Edition',
    price_category: '$$',
    location_data: { city: 'Brooklyn', address: '79 N 11th St, Brooklyn, NY', zipcode: '11249' },
    event_date: '2026-04-18',
    event_time_utc: '2026-04-18T14:00:00Z',
    relevant_links: ['https://brooklynbrewery.com'],
    description: 'Sample 50+ local and regional craft beers, enjoy live music, food vendors, and celebrate spring in Williamsburg.',
    photos: ['https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=400'],
    representative_emoji: '🍺',
    hex_color: '#FFC107',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.7179,
    lng: -73.9614,
  },
  {
    id: 'sample-13',
    name: 'Governors Island',
    event_name: 'Governors Island Spring Opening Weekend',
    price_category: 'free',
    location_data: { city: 'Manhattan', address: 'Governors Island, NY', zipcode: '10004' },
    event_date: '2026-05-01',
    event_time_utc: '2026-05-01T10:00:00Z',
    relevant_links: ['https://govisland.com'],
    description: 'The beloved car-free island opens for the season with pop-up art installations, food festivals, hammock groves, and stunning harbor views.',
    photos: ['https://images.unsplash.com/photo-1524813686514-a57563d77965?w=400'],
    representative_emoji: '🏝️',
    hex_color: '#00E676',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.6892,
    lng: -74.0168,
  },
  {
    id: 'sample-14',
    name: 'Queens Night Market',
    event_name: 'Queens Night Market Opening Night 2026',
    price_category: '$',
    location_data: { city: 'Queens', address: 'New York Hall of Science, 47-01 111th St, Queens, NY', zipcode: '11368' },
    event_date: '2026-04-11',
    event_time_utc: '2026-04-11T17:00:00Z',
    relevant_links: ['https://www.queensnightmarket.com'],
    description: '80+ vendors celebrating cuisines from around the world in one of NYC\'s most beloved outdoor markets. Live performances and cultural programming.',
    photos: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400'],
    representative_emoji: '🥘',
    hex_color: '#FF6D00',
    is_approved: true,
    _sample: true,
    borough: 'Queens',
    lat: 40.7466,
    lng: -73.8449,
  },
  {
    id: 'sample-15',
    name: 'Bronx Zoo',
    event_name: 'Wildlife Conservation Society Spring Gala',
    price_category: '$$$',
    location_data: { city: 'Bronx', address: '2300 Southern Blvd, Bronx, NY', zipcode: '10460' },
    event_date: '2026-04-22',
    event_time_utc: '2026-04-22T18:00:00Z',
    relevant_links: ['https://www.bronxzoo.com'],
    description: 'An exclusive evening at the Bronx Zoo benefiting wildlife conservation. Dinner among the animals, live entertainment, and conservation talks.',
    photos: ['https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=400'],
    representative_emoji: '🦁',
    hex_color: '#8BC34A',
    is_approved: true,
    _sample: true,
    borough: 'Bronx',
    lat: 40.8611,
    lng: -73.8975,
  },
  {
    id: 'sample-16',
    name: 'Staten Island Ferry',
    event_name: 'Free Staten Island Ferry Art Walk',
    price_category: 'free',
    location_data: { city: 'Staten Island', address: 'St George Terminal, Staten Island, NY', zipcode: '10301' },
    event_date: '2026-04-05',
    event_time_utc: '2026-04-05T11:00:00Z',
    relevant_links: ['https://www.siferry.com'],
    description: 'Enjoy free round-trip ferry rides with pop-up art installations onboard and along the St. George waterfront. Views of the Statue of Liberty included.',
    photos: ['https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=400'],
    representative_emoji: '⛴️',
    hex_color: '#FF7043',
    is_approved: true,
    _sample: true,
    borough: 'Staten Island',
    lat: 40.6433,
    lng: -74.0771,
  },
  {
    id: 'sample-17',
    name: 'Lincoln Center',
    event_name: 'NYC Ballet Spring Season Opening',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '20 Lincoln Center Plaza, New York, NY', zipcode: '10023' },
    event_date: '2026-04-07',
    event_time_utc: '2026-04-07T20:00:00Z',
    relevant_links: ['https://www.lincolncenter.org'],
    description: 'The New York City Ballet opens its spring season with a program featuring world premieres and beloved classics choreographed by George Balanchine.',
    photos: ['https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400'],
    representative_emoji: '🩰',
    hex_color: '#E91E63',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.6945,
    lng: -73.9857,
  },
  {
    id: 'sample-18',
    name: 'Coney Island',
    event_name: 'Coney Island Easter Parade & Egg Hunt',
    price_category: 'free',
    location_data: { city: 'Brooklyn', address: 'Boardwalk, Coney Island, Brooklyn, NY', zipcode: '11224' },
    event_date: '2026-04-05',
    event_time_utc: '2026-04-05T12:00:00Z',
    relevant_links: ['https://www.coneyisland.com'],
    description: 'Family-friendly Easter egg hunt and parade along the iconic Coney Island boardwalk. Prizes, food, rides, and freakshow performances.',
    photos: ['https://images.unsplash.com/photo-1533740566848-5f7d3e04e3d7?w=400'],
    representative_emoji: '🥚',
    hex_color: '#9C27B0',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.6712,
    lng: -73.9639,
  },
  {
    id: 'sample-19',
    name: 'Javits Center',
    event_name: 'New York Comic Con Spring Preview',
    price_category: '$$',
    location_data: { city: 'Manhattan', address: '429 11th Ave, New York, NY', zipcode: '10001' },
    event_date: '2026-04-25',
    event_time_utc: '2026-04-25T10:00:00Z',
    relevant_links: ['https://www.newyorkcomiccon.com'],
    description: 'Preview weekend for the upcoming New York Comic Con. Exclusive panels, artist alley previews, cosplay contests, and collector trading.',
    photos: ['https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=400'],
    representative_emoji: '🦸',
    hex_color: '#2196F3',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7845,
    lng: -73.9575,
  },
  {
    id: 'sample-20',
    name: 'Prospect Park',
    event_name: 'Brooklyn Cherry Blossom Festival',
    price_category: 'free',
    location_data: { city: 'Brooklyn', address: 'Prospect Park, Brooklyn, NY', zipcode: '11215' },
    event_date: '2026-04-12',
    event_time_utc: '2026-04-12T11:00:00Z',
    relevant_links: ['https://www.prospectpark.org'],
    description: 'Celebrate the peak bloom of the park\'s cherry blossom trees with Japanese cultural performances, tea ceremonies, and hanami picnics.',
    photos: [
      'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=600',
      'https://images.unsplash.com/photo-1461567822611-7a7f53f4b6fa?w=600',
      'https://images.unsplash.com/photo-1490750967868-88df5691cc10?w=600',
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600',
      'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=600',
    ],
    representative_emoji: '🌸',
    hex_color: '#F48FB1',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.8108,
    lng: -73.8195,
  },
  {
    id: 'sample-21',
    name: 'MoMA',
    event_name: 'MoMA PS1 Warm Up Summer Series Kickoff',
    price_category: '$',
    location_data: { city: 'Queens', address: '22-25 Jackson Ave, Long Island City, NY', zipcode: '11101' },
    event_date: '2026-05-02',
    event_time_utc: '2026-05-02T15:00:00Z',
    relevant_links: ['https://www.moma.org'],
    description: 'The legendary outdoor music series kicks off at MoMA PS1\'s courtyard. DJs, live performances, art installations, and the city\'s most creative crowd.',
    photos: ['https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400'],
    representative_emoji: '🎧',
    hex_color: '#00BFA5',
    is_approved: true,
    _sample: true,
    borough: 'Queens',
    lat: 40.8175,
    lng: -73.9215,
  },
  {
    id: 'sample-22',
    name: 'Yankee Stadium',
    event_name: 'New York Yankees Home Opener 2026',
    price_category: '$$',
    location_data: { city: 'Bronx', address: '1 E 161st St, Bronx, NY', zipcode: '10451' },
    event_date: '2026-04-07',
    event_time_utc: '2026-04-07T13:05:00Z',
    relevant_links: ['https://www.mlb.com/yankees'],
    description: 'The Bronx Bombers kick off the 2026 season at home. First pitch ceremonies, pre-game festivities, and giveaways for the first 10,000 fans.',
    photos: ['https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=400'],
    representative_emoji: '⚾',
    hex_color: '#0D47A1',
    is_approved: true,
    _sample: true,
    borough: 'Bronx',
    lat: 40.7425,
    lng: -73.9468,
  },
  {
    id: 'sample-23',
    name: 'Rego Park',
    event_name: 'Queens International Dance Festival',
    price_category: '$',
    location_data: { city: 'Queens', address: 'Queens Theatre, 14 United Nations Ave S, NY', zipcode: '11368' },
    event_date: '2026-03-20',
    event_time_utc: '2026-03-20T17:00:00Z',
    relevant_links: ['https://www.queenstheatre.org'],
    description: 'Celebrating the diverse dance traditions of Queens with performances from 30+ countries. Indian classical, Latin, African, and contemporary styles.',
    photos: ['https://images.unsplash.com/photo-1504609813442-a9b0e2e21a89?w=400'],
    representative_emoji: '🕺',
    hex_color: '#FF5722',
    is_approved: true,
    _sample: true,
    borough: 'Queens',
    lat: 40.6978,
    lng: -73.7911,
  },
  {
    id: 'sample-24',
    name: 'Flushing Meadows',
    event_name: 'Lunar New Year Flushing Cultural Fair',
    price_category: 'free',
    location_data: { city: 'Queens', address: 'Flushing Meadows Corona Park, Queens, NY', zipcode: '11368' },
    event_date: '2026-03-08',
    event_time_utc: '2026-03-08T12:00:00Z',
    relevant_links: ['https://www.nycgovparks.org'],
    description: 'Celebrate Lunar New Year with dragon dances, traditional foods, lantern displays, and cultural performances from 15+ Asian communities.',
    photos: ['https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400'],
    representative_emoji: '🏮',
    hex_color: '#F44336',
    is_approved: true,
    _sample: true,
    borough: 'Queens',
    lat: 40.6432,
    lng: -74.0949,
  },
  {
    id: 'sample-25',
    name: 'Whitney Museum',
    event_name: 'Whitney Biennial 2026 Opening',
    price_category: '$$',
    location_data: { city: 'Manhattan', address: '99 Gansevoort St, New York, NY', zipcode: '10014' },
    event_date: '2026-03-18',
    event_time_utc: '2026-03-18T11:00:00Z',
    relevant_links: ['https://whitney.org'],
    description: 'The most important exhibition of contemporary American art opens with 70+ artists across all media. The pulse of the American art world every two years.',
    photos: ['https://images.unsplash.com/photo-1577083552792-a0d461cb1dd6?w=400'],
    representative_emoji: '🖼️',
    hex_color: '#FF6F00',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.6399,
    lng: -74.0929,
  },
  {
    id: 'sample-26',
    name: 'High Line',
    event_name: 'High Line Community Spring Market',
    price_category: 'free',
    location_data: { city: 'Manhattan', address: 'The High Line, W 20th St, New York, NY', zipcode: '10011' },
    event_date: '2026-04-19',
    event_time_utc: '2026-04-19T10:00:00Z',
    relevant_links: ['https://www.thehighline.org'],
    description: 'Shop from 40+ local Brooklyn and Manhattan artisans, enjoy live acoustic music, and explore the blooming gardens of the elevated park.',
    photos: ['https://images.unsplash.com/photo-1535401991746-da3d9055713c?w=400'],
    representative_emoji: '🌿',
    hex_color: '#4CAF50',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7187,
    lng: -73.9843,
  },
  {
    id: 'sample-27',
    name: 'Jazz at Lincoln Center',
    event_name: 'Wynton Marsalis Quartet Live',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '10 Columbus Circle, New York, NY', zipcode: '10019' },
    event_date: '2026-03-27',
    event_time_utc: '2026-03-27T20:00:00Z',
    relevant_links: ['https://www.jazz.org'],
    description: 'Jazz legend Wynton Marsalis leads his quartet through an evening of original compositions and American jazz standards at the Allen Room.',
    photos: ['https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400'],
    representative_emoji: '🎺',
    hex_color: '#1A237E',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.6987,
    lng: -73.9790,
  },
  {
    id: 'sample-28',
    name: 'Brooklyn Flea',
    event_name: 'Brooklyn Flea Spring Season Grand Opening',
    price_category: 'free',
    location_data: { city: 'Brooklyn', address: '80 Pearl St, Brooklyn, NY', zipcode: '11201' },
    event_date: '2026-03-21',
    event_time_utc: '2026-03-21T10:00:00Z',
    relevant_links: ['https://brooklynflea.com'],
    description: 'NYC\'s premier outdoor flea market returns for spring. 150+ vendors with vintage goods, handmade crafts, antiques, and amazing street food.',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'],
    representative_emoji: '🛍️',
    hex_color: '#795548',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.7558,
    lng: -73.9052,
  },
  {
    id: 'sample-29',
    name: 'Smorgasburg',
    event_name: 'Smorgasburg Spring Return - Williamsburg',
    price_category: '$',
    location_data: { city: 'Brooklyn', address: '90 Kent Ave, Brooklyn, NY', zipcode: '11211' },
    event_date: '2026-04-04',
    event_time_utc: '2026-04-04T11:00:00Z',
    relevant_links: ['https://www.smorgasburg.com'],
    description: 'America\'s largest weekly open-air food market returns to Williamsburg with 100+ local food vendors, views of Manhattan, and a party atmosphere.',
    photos: ['https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400'],
    representative_emoji: '🌮',
    hex_color: '#FF9800',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.7020,
    lng: -73.8012,
  },
  {
    id: 'sample-30',
    name: 'Staten Island Museum',
    event_name: 'Staten Island Makers Fair',
    price_category: 'free',
    location_data: { city: 'Staten Island', address: '75 Stuyvesant Pl, Staten Island, NY', zipcode: '10301' },
    event_date: '2026-04-26',
    event_time_utc: '2026-04-26T10:00:00Z',
    relevant_links: ['https://statenislandmuseum.org'],
    description: 'A celebration of DIY culture, technology, art, and engineering. Robots, 3D printing demos, craft workshops, and interactive science exhibits.',
    photos: ['https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=400'],
    representative_emoji: '🔧',
    hex_color: '#607D8B',
    is_approved: true,
    _sample: true,
    borough: 'Staten Island',
    lat: 40.6152,
    lng: -74.1560,
  },
  {
    id: 'sample-31',
    name: 'MSG Sphere (hypothetical)',
    event_name: 'Electronic Music Festival NYC 2026',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: 'Randall\'s Island, New York, NY', zipcode: '10035' },
    event_date: '2026-05-08',
    event_time_utc: '2026-05-08T16:00:00Z',
    relevant_links: ['https://www.randallsisland.org'],
    description: 'Three-day electronic music festival featuring 40+ DJs and live acts across 5 stages on Randall\'s Island. Camping available.',
    photos: ['https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400'],
    representative_emoji: '🎛️',
    hex_color: '#00E5FF',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7225,
    lng: -73.9888,
  },
  {
    id: 'sample-32',
    name: 'Harlem Cultural Alliance',
    event_name: 'Harlem Week Spring Preview',
    price_category: 'free',
    location_data: { city: 'Manhattan', address: '253 W 125th St, New York, NY', zipcode: '10027' },
    event_date: '2026-03-28',
    event_time_utc: '2026-03-28T12:00:00Z',
    relevant_links: ['https://www.harlemweek.com'],
    description: 'A preview of the summer\'s Harlem Week with music, spoken word, poetry, and cultural programming celebrating the legacy of the Harlem Renaissance.',
    photos: ['https://images.unsplash.com/photo-1493787039806-2edcbe808750?w=400'],
    representative_emoji: '✊',
    hex_color: '#FF6F00',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.6543,
    lng: -74.0037,
  },
  {
    id: 'sample-33',
    name: 'Printed Matter',
    event_name: 'NY Art Book Fair at MoMA PS1',
    price_category: 'free',
    location_data: { city: 'Queens', address: '22-25 Jackson Ave, Long Island City, NY', zipcode: '11101' },
    event_date: '2026-04-16',
    event_time_utc: '2026-04-16T11:00:00Z',
    relevant_links: ['https://printedmatter.org'],
    description: 'The world\'s premier event for artist books, zines, and alternative publications. 400+ exhibitors from 30+ countries, talks, launches, and signings.',
    photos: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400'],
    representative_emoji: '📚',
    hex_color: '#5C6BC0',
    is_approved: true,
    _sample: true,
    borough: 'Queens',
    lat: 40.7427,
    lng: -73.9233,
  },
  {
    id: 'sample-34',
    name: 'Bronx Terminal Market',
    event_name: 'Bronx Latino Heritage Festival',
    price_category: 'free',
    location_data: { city: 'Bronx', address: '610 Exterior St, Bronx, NY', zipcode: '10451' },
    event_date: '2026-04-03',
    event_time_utc: '2026-04-03T12:00:00Z',
    relevant_links: ['https://www.bronxarts.org'],
    description: 'Celebrating the diverse Latino cultures of the Bronx with live salsa, merengue, cumbia, food from 20+ vendors, and art installations.',
    photos: ['https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400'],
    representative_emoji: '🎶',
    hex_color: '#E91E63',
    is_approved: true,
    _sample: true,
    borough: 'Bronx',
    lat: 40.8296,
    lng: -73.9262,
  },
  {
    id: 'sample-35',
    name: 'IFC Center',
    event_name: 'New York International Children\'s Film Festival',
    price_category: '$',
    location_data: { city: 'Manhattan', address: '323 6th Ave, New York, NY', zipcode: '10014' },
    event_date: '2026-03-01',
    event_time_utc: '2026-03-01T14:00:00Z',
    relevant_links: ['https://nyicff.org'],
    description: 'Award-winning animation and foreign-language films for young movie-lovers aged 3-18. Screenings across Manhattan venues with Q&As and workshops.',
    photos: ['https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400'],
    representative_emoji: '🎬',
    hex_color: '#AB47BC',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.6596,
    lng: -73.8963,
  },
  {
    id: 'sample-36',
    name: 'Barclays Center',
    event_name: 'Brooklyn Nets vs Miami Heat',
    price_category: '$$',
    location_data: { city: 'Brooklyn', address: '620 Atlantic Ave, Brooklyn, NY', zipcode: '11217' },
    event_date: '2026-03-13',
    event_time_utc: '2026-03-13T19:30:00Z',
    relevant_links: ['https://www.barclayscenter.com'],
    description: 'Brooklyn Nets face off against the Miami Heat in a crucial mid-season matchup at Barclays Center. Arrive early for pre-game festivities.',
    photos: ['https://images.unsplash.com/photo-1546519638405-a9f14e610c99?w=400'],
    representative_emoji: '🏀',
    hex_color: '#000000',
    is_approved: true,
    _sample: true,
    borough: 'Brooklyn',
    lat: 40.6403,
    lng: -74.0771,
  },
  {
    id: 'sample-37',
    name: 'Spring Studios',
    event_name: 'New York Fashion Week Resort 2026',
    price_category: '$$$',
    location_data: { city: 'Manhattan', address: '50 Varick St, New York, NY', zipcode: '10013' },
    event_date: '2026-03-09',
    event_time_utc: '2026-03-09T11:00:00Z',
    relevant_links: ['https://cfda.com'],
    description: 'Resort season runway shows from emerging and established designers in downtown Manhattan. Invite-only shows, public pop-ups, and adjacent events.',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'],
    representative_emoji: '👗',
    hex_color: '#F06292',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.7785,
    lng: -73.9725,
  },
  {
    id: 'sample-38',
    name: 'Astoria Park',
    event_name: 'Astoria International Food Festival',
    price_category: 'free',
    location_data: { city: 'Queens', address: 'Astoria Park, Astoria, Queens, NY', zipcode: '11102' },
    event_date: '2026-04-24',
    event_time_utc: '2026-04-24T11:00:00Z',
    relevant_links: ['https://www.queensbp.org'],
    description: 'Celebrating Astoria\'s incredible cultural diversity with Greek, Middle Eastern, Mexican, Korean, and 20+ other cuisines. Live performances on two stages.',
    photos: ['https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=400'],
    representative_emoji: '🌍',
    hex_color: '#26C6DA',
    is_approved: true,
    _sample: true,
    borough: 'Queens',
    lat: 40.5749,
    lng: -73.9786,
  },
  {
    id: 'sample-39',
    name: 'The Comedy Cellar',
    event_name: 'Comedy Cellar Late Night Stand-Up Marathon',
    price_category: '$$',
    location_data: { city: 'Manhattan', address: '117 MacDougal St, New York, NY', zipcode: '10012' },
    event_date: '2026-04-17',
    event_time_utc: '2026-04-17T22:00:00Z',
    relevant_links: ['https://www.comedycellar.com'],
    description: 'A special 6-hour late-night comedy marathon featuring surprise drop-ins and resident comedians in the legendary basement of Greenwich Village.',
    photos: ['https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=400'],
    representative_emoji: '😂',
    hex_color: '#FFEB3B',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.8043,
    lng: -73.9530,
  },
  {
    id: 'sample-40',
    name: 'Artists & Fleas Chelsea',
    event_name: 'Chelsea Gallery Walk Spring Opening Night',
    price_category: 'free',
    location_data: { city: 'Manhattan', address: 'W 24th St & 10th Ave, New York, NY', zipcode: '10011' },
    event_date: '2026-04-02',
    event_time_utc: '2026-04-02T18:00:00Z',
    relevant_links: ['https://chelseagalleries.com'],
    description: 'The spring gallery season opens across 50+ Chelsea galleries simultaneously. Wine, openings, talks with artists, and the most concentrated art district in the world.',
    photos: ['https://images.unsplash.com/photo-1536924430914-91f9e2041b83?w=400'],
    representative_emoji: '🖌️',
    hex_color: '#7C4DFF',
    is_approved: true,
    _sample: true,
    borough: 'Manhattan',
    lat: 40.8565,
    lng: -73.7960,
  },
];

// Export — when SAMPLE_MODE is false, return empty array
export const SAMPLE_EVENTS = SAMPLE_MODE ? ALL_SAMPLE_EVENTS : [];